// @ts-nocheck
export class BottomActionBar {
  constructor(private scene, private player, private abilities, private getItemCount){
    const w=scene.scale.width,h=scene.scale.height;
    this.root=scene.add.container(w/2,h-8).setScrollFactor(0).setDepth(700);
    const panel=scene.add.rectangle(0,-64,940,122,0x0f1724,.98).setStrokeStyle(2,0x35445f,1);this.root.add(panel);
    this.hpOuter=scene.add.circle(-410,-60,40,0x1b2330,1).setStrokeStyle(3,0x6f293b,1);this.hpOrb=scene.add.arc(-410,-60,32,-90,270,false,0xb83a4d,1);this.hpText=scene.add.text(-410,-60,'',{fontFamily:'Arial',fontSize:11,color:'#fff',fontStyle:'bold',align:'center'}).setOrigin(.5);this.root.add([this.hpOuter,this.hpOrb,this.hpText]);
    this.manaOuter=scene.add.circle(410,-60,40,0x1b2330,1).setStrokeStyle(3,0x31547e,1);this.manaOrb=scene.add.arc(410,-60,32,-90,270,false,0x3f8dcc,1);this.manaText=scene.add.text(410,-60,'',{fontFamily:'Arial',fontSize:11,color:'#fff',fontStyle:'bold',align:'center'}).setOrigin(.5);this.root.add([this.manaOuter,this.manaOrb,this.manaText]);
    this.classText=scene.add.text(0,-112,'',{fontFamily:'Arial',fontSize:11,color:'#ffd166',fontStyle:'bold'}).setOrigin(.5);this.root.add(this.classText);
    this.xpBg=scene.add.rectangle(-150,-13,380,6,0x344057,1).setOrigin(0,.5);this.xpFill=scene.add.rectangle(-150,-13,0,6,0x7ee0ff,1).setOrigin(0,.5);this.levelText=scene.add.text(55,-20,'',{fontFamily:'Arial',fontSize:10,color:'#c8d1ea'}).setOrigin(.5);this.root.add([this.xpBg,this.xpFill,this.levelText]);
    const defs=[['Q',-170],['1',-75],['2',20],['ESPAÇO',115]];this.slots=[];this.backs=[];defs.forEach(([key,x])=>{const b=scene.add.rectangle(x,-60,78,66,0x24314d,1).setStrokeStyle(2,0x586b8c,1);const t=scene.add.text(x,-60,key,{fontFamily:'Arial',fontSize:10,color:'#fff',fontStyle:'bold',align:'center',wordWrap:{width:72}}).setOrigin(.5);this.root.add([b,t]);this.backs.push(b);this.slots.push(t)});
    this.potionText=scene.add.text(285,-60,'',{fontFamily:'Arial',fontSize:11,color:'#ecf0ff',align:'left'}).setOrigin(.5);this.root.add(this.potionText);this.controls=scene.add.text(0,-1,'C • CONTROLES     P • PAUSA',{fontFamily:'Arial',fontSize:10,color:'#7ee0ff',fontStyle:'bold',backgroundColor:'#182033',padding:{left:8,right:8,top:4,bottom:4}}).setOrigin(.5);this.root.add(this.controls);this.visible=true;this.update()
  }
  setVisible(v){this.visible=v;this.root.setVisible(v)}
  update(){if(!this.visible)return;const hr=Phaser.Math.Clamp(this.player.hp/Math.max(1,this.player.maxHp),0,1),mr=Phaser.Math.Clamp(this.player.mana/Math.max(1,this.player.maxMana),0,1);this.hpOrb.setEndAngle(-90+360*hr);this.manaOrb.setEndAngle(-90+360*mr);this.hpText.setText(`HP\n${this.player.hp}/${this.player.maxHp}`);this.manaText.setText(`MP\n${this.player.mana}/${this.player.maxMana}`);const names={warrior:'GUERREIRO',mage:'MAGO',ranger:'CAÇADOR'};this.classText.setText(`${names[this.player.characterClass]||'AVENTUREIRO'} • NÍVEL ${this.player.level}`);const need=this.player.level*100;this.xpFill.width=380*Phaser.Math.Clamp(this.player.xp/need,0,1);this.levelText.setText(`XP ${this.player.xp}/${need} • +1 Skill • +3 Atributos no nível`);const l=this.abilities.loadout();const ids=['primary','secondary','mobility'];const keys=['Q','1','2'];for(let i=0;i<3;i++){const d=l[ids[i]],cd=this.abilities.cooldown(ids[i]),rank=this.player.scene.skillManager?.getRank(ids[i])||0;this.slots[i].setText(`${keys[i]}\n${d[0]}\nRank ${rank}/5 • ${d[1]+Math.max(0,rank-1)*3} MP${rank<=0?'\nBLOQUEADA':cd>0?`\n${(cd/1000).toFixed(1)}s`:''}`);this.slots[i].setColor(rank<=0?'#7b87a5':cd>0?'#9aa8c7':'#ecf0ff');this.backs[i].setFillStyle(rank<=0?0x171e2b:cd>0?0x1b2435:0x24314d,1)}this.slots[3].setText('ESPAÇO\nATAQUE');this.potionText.setText(`H  HP: ${this.getItemCount('healing_potion')}\nM  MP: ${this.getItemCount('mana_potion')}`)}
 destroy(){this.root.destroy(true)}
}
