// @ts-nocheck
import {getItemDefinition,rarityColor} from '../items/itemCatalog';
export class CharacterInventoryPanel{
 constructor(scene,player,inventory,equipment,save){this.scene=scene;this.player=player;this.inv=inventory;this.equipment=equipment;this.save=save;const w=scene.scale.width,h=scene.scale.height;this.bg=scene.add.rectangle(w/2,h/2,w-70,h-70,0x0d1422,.99).setScrollFactor(0).setDepth(950).setStrokeStyle(2,0x526a93,1).setVisible(false);this.title=scene.add.text(w/2,52,'PERSONAGEM • EQUIPAMENTOS • INVENTÁRIO',{fontFamily:'Arial',fontSize:23,color:'#ecf0ff',fontStyle:'bold'}).setOrigin(.5).setScrollFactor(0).setDepth(951).setVisible(false);this.close=scene.add.text(w-58,34,'I  FECHAR',{fontFamily:'Arial',fontSize:12,color:'#9aa8c7',backgroundColor:'#182033',padding:7}).setOrigin(1,0).setScrollFactor(0).setDepth(951).setInteractive({useHandCursor:true}).setVisible(false);this.close.on('pointerdown',()=>this.hide());
 this.statusBg=scene.add.rectangle(w/2,128,w-140,115,0x182033,.98).setScrollFactor(0).setDepth(951).setStrokeStyle(1,0x32405f,1).setVisible(false);this.classText=scene.add.text(90,88,'',{fontFamily:'Arial',fontSize:18,color:'#ffd166',fontStyle:'bold'}).setScrollFactor(0).setDepth(952).setVisible(false);this.statsText=scene.add.text(90,120,'',{fontFamily:'Arial',fontSize:13,color:'#c8d1ea',lineSpacing:5}).setScrollFactor(0).setDepth(952).setVisible(false);this.xpBg=scene.add.rectangle(w-260,105,300,10,0x3a465f,1).setScrollFactor(0).setDepth(952).setVisible(false);this.xp=scene.add.rectangle(w-410,105,0,10,0x7ee0ff,1).setOrigin(0,.5).setScrollFactor(0).setDepth(953).setVisible(false);this.xpText=scene.add.text(w-410,116,'',{fontFamily:'Arial',fontSize:11,color:'#9aa8c7'}).setScrollFactor(0).setDepth(953).setVisible(false);this.attrText=scene.add.text(w-410,145,'',{fontFamily:'Arial',fontSize:12,color:'#ffd166'}).setScrollFactor(0).setDepth(953).setVisible(false);
 this.equipBg=scene.add.rectangle(255,365,330,300,0x182033,.98).setScrollFactor(0).setDepth(951).setStrokeStyle(1,0x32405f,1).setVisible(false);this.invBg=scene.add.rectangle(w-255,365,400,300,0x182033,.98).setScrollFactor(0).setDepth(951).setStrokeStyle(1,0x32405f,1).setVisible(false);this.equipTitle=scene.add.text(255,225,'EQUIPAMENTOS',{fontFamily:'Arial',fontSize:16,color:'#ecf0ff',fontStyle:'bold'}).setOrigin(.5).setScrollFactor(0).setDepth(952).setVisible(false);this.invTitle=scene.add.text(w-255,225,'INVENTÁRIO',{fontFamily:'Arial',fontSize:16,color:'#ecf0ff',fontStyle:'bold'}).setOrigin(.5).setScrollFactor(0).setDepth(952).setVisible(false);this.appearance=scene.add.image(255,275,'player',1).setScale(.85).setScrollFactor(0).setDepth(952).setVisible(false);this.appearanceText=scene.add.text(255,335,'Aparência do personagem',{fontFamily:'Arial',fontSize:11,color:'#9aa8c7'}).setOrigin(.5).setScrollFactor(0).setDepth(952).setVisible(false);
 this.slotDefs=[['weapon','ARMA'],['armor','ARMADURA'],['trinket','TRINKET']];this.slots=[];this.rows=[];this.refresh();}
 show(){this.setVisible(true);this.refresh()}
 hide(){this.setVisible(false)}
 toggle(){this.setVisible(!this.bg.visible);if(this.bg.visible)this.refresh()}
 setVisible(v){[this.bg,this.title,this.close,this.statusBg,this.classText,this.statsText,this.xpBg,this.xp,this.xpText,this.attrText,this.equipBg,this.invBg,this.equipTitle,this.invTitle,this.appearance,this.appearanceText].forEach(o=>o.setVisible(v));this.slots.forEach(s=>{s.box.setVisible(v);s.label.setVisible(v);s.value.setVisible(v)});this.rows.forEach(r=>r.setVisible(v));this.bg.setVisible(v)}
 refresh(){const names={warrior:'Guerreiro',mage:'Mago',ranger:'Caçador'};this.classText.setText(`${names[this.player.characterClass]}  •  Nível ${this.player.level}  •  Ouro ${this.player.gold}`);this.statsText.setText(`HP ${this.player.hp}/${this.player.maxHp}   •   MANA ${this.player.mana}/${this.player.maxMana}\nATQ ${this.player.attackDamage}   •   DEF ${this.player.defense}   •   SPD ${this.player.speed}`);const need=this.player.level*100;const ratio=Math.max(0,Math.min(1,this.player.xp/need));this.xp.width=300*ratio;this.xpText.setText(`XP ${this.player.xp}/${need}`);this.attrText.setText(`Pontos de atributos: ${this.player.attributePoints}     +HP +5   +MANA +3   +ATQ +1   +DEF +1`);this.createAttrButtons();this.createSlots();this.createRows()}
 createAttrButtons(){if(this.attrButtons){this.attrButtons.forEach(b=>b.destroy());}this.attrButtons=[];const defs=[['HP','hp'],['MANA','mana'],['ATQ','attack'],['DEF','defense']];defs.forEach(([name,id],i)=>{const b=this.scene.add.text(this.scene.scale.width-385+i*82,145,`+${name}`,{fontFamily:'Arial',fontSize:11,color:'#73e6a8',backgroundColor:'#24314d',padding:5}).setScrollFactor(0).setDepth(954).setInteractive({useHandCursor:true}).setVisible(this.bg.visible);b.on('pointerdown',()=>{if(this.player.allocateAttribute(id)){this.refresh();this.save()}});this.attrButtons.push(b)})}
 createSlots(){this.slots.forEach(s=>{s.box.destroy();s.label.destroy();s.value.destroy()});this.slots=[];this.slotDefs.forEach(([slot,name],i)=>{const y=300+i*82;const box=this.scene.add.rectangle(125,y,230,60,0x24314d,1).setOrigin(.5).setScrollFactor(0).setDepth(953).setStrokeStyle(1,0x4a5e82,1).setInteractive({useHandCursor:true});const label=this.scene.add.text(15,y-18,name,{fontFamily:'Arial',fontSize:10,color:'#9aa8c7'}).setScrollFactor(0).setDepth(954);const id=this.equipment.slots[slot];const item=getItemDefinition(id);const value=this.scene.add.text(15,y+1,item?`${item.name} • clique para retirar`:'Vazio',{fontFamily:'Arial',fontSize:11,color:item?this.color(item.rarity):'#9aa8c7',wordWrap:{width:205}}).setScrollFactor(0).setDepth(954);box.on('pointerdown',()=>{if(this.equipment.unequip(slot,this.inv)){this.refresh();this.save()}});this.slots.push({box,label,value})})}
 createRows(){this.rows.forEach(r=>r.destroy());this.rows=[];const items=this.inv.items||[];if(!items.length){this.rows.push(this.scene.add.text(this.scene.scale.width-430,285,'Inventário vazio',{fontFamily:'Arial',fontSize:14,color:'#9aa8c7'}).setScrollFactor(0).setDepth(954));return}items.slice(0,8).forEach((entry,i)=>{const d=getItemDefinition(entry.id);const row=this.scene.add.text(this.scene.scale.width-440,265+i*35,`${d?.name||entry.id} x${entry.qty}`,{fontFamily:'Arial',fontSize:12,color:d?this.color(d.rarity):'#ecf0ff',backgroundColor:'#24314d',padding:{left:7,right:7,top:5,bottom:5},fixedWidth:350}).setScrollFactor(0).setDepth(954).setInteractive({useHandCursor:true});row.on('pointerdown',()=>{if(d&&['weapon','armor','trinket'].includes(d.type)&&this.equipment.equip(entry.id,this.inv)){this.refresh();this.save()}});this.rows.push(row)})}
 color(r){return rarityColor(r)}
}
