// Art only; generated by scripts/build_old_road_b4d_art.py.
export const OLD_ROAD_B4D_TEXTURES=Object.freeze({
  "straightLong": [
    "old_road_b4d_straight_long_01",
    "old_road_b4d_straight_long_02",
    "old_road_b4d_straight_long_03",
    "old_road_b4d_straight_long_04",
    "old_road_b4d_straight_long_05",
    "old_road_b4d_straight_long_06",
    "old_road_b4d_straight_long_07",
    "old_road_b4d_straight_long_08",
    "old_road_b4d_straight_long_09",
    "old_road_b4d_straight_long_10",
    "old_road_b4d_straight_long_11"
  ],
  "straightShort": [
    "old_road_b4d_straight_short_01",
    "old_road_b4d_straight_short_02",
    "old_road_b4d_straight_short_03",
    "old_road_b4d_straight_short_04",
    "old_road_b4d_straight_short_05"
  ],
  "curveRight": [
    "old_road_b4d_curve_right_01"
  ],
  "yJunction": [
    "old_road_b4d_y_junction_01"
  ],
  "startRun": [
    "old_road_b4d_start_run_01"
  ],
  "gateTransition": [
    "old_road_b4d_gate_transition_01"
  ]
});
