// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {CastleMiniBoss} from '../entities/CastleMiniBoss';import {CastleBoss} from '../entities/CastleBoss';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {SfxManager} from '../audio/SfxManager';import {getItemDefinition} from '../items/itemCatalog';
export class CastleScene extends Phaser.Scene{
 constructor(){super('CastleScene')}
 create(){this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,140,560);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loadGame();this.add.tileSprite(0,0,1920,1152,'path').setOrigin(0);this.add.rectangle(0,0,1920,1152,0x160f21,.35).setOrigin(0);this.enemies=[new Enemy(this,500,260,'Guarda',{hp:76,attackDamage:16,xpReward:38}),new Enemy(this,760,380,'Mago da Coroa',{hp:100,attackDamage:20,xpReward:55}),new Enemy(this,950,500,'Cavaleiro',{hp:120,attackDamage:23,xpReward:65})];this.mini=new CastleMiniBoss(this,1200,420);this.boss=new CastleBoss(this,1580,420,'Rei Sombrio',{hp:460,attackDamage:27,xpReward:220});this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),worldWidth:1920,worldHeight:1152,localName:'CASTELO',markers:[{x:100,y:560,color:0xffd166,label:'Caverna'},{x:1580,y:420,color:0xff6b6b,label:'Rei Sombrio'}]});this.exit=this.add.zone(100,560,120,120);this.setupInput();this.death=new DeathOverlay(this);this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.CastleScene,t=this.registry.get('transitionSpawn');if(save){this.player.loadState(save.player);this.classManager.load(this.player,save.player?.characterClass||save.characterClass);this.skillManager.load(save.skills);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv)}else this.player.applyClass(this.registry.get('selectedClass')||'warrior');if(t?.scene==='CastleScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y)}
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO)}
 update(){if(this.hud.handle({collect:()=>this.collect(),afterAction:()=>this.saveGame(),talk:()=>this.message('O castelo não tem NPCs seguros.')})){this.hud.update();return}if(!this.player.isDead()){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy));for(const e of this.enemies){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player);if(this.boss.isAlive()){this.boss.updateAI(this.player);this.combat.enemyAttack(this.boss,this.player)}const t=[...this.enemies,this.mini,this.boss];if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);this.loot.update(this.player.x,this.player.y);if(!this.boss.isAlive()&&!this.victoryTriggered){this.victoryTriggered=true;const relic=getItemDefinition('royal_signet');if(relic)this.inv.add(relic.id,1);this.saveGame();this.time.delayedCall(1000,()=>this.scene.start('VictoryScene'))}}else this.handleDeath();this.hud.update();if(this.player.x<150&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'CaveScene',x:1740,y:560});this.scene.start('CaveScene')}}
 collect(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame()}}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn no castelo em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(180,560);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:old?.quests||[],scenePositions:{...(old?.scenePositions||{}),[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 message(t){this.msg??=this.add.text(this.scale.width/2,this.scale.height-140,'',{fontFamily:'Arial',fontSize:13,color:'#fff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1000);this.msg.setText(t);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:900,duration:400})}
}
