// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {CastleMiniBoss} from '../entities/CastleMiniBoss';import {CastleBoss} from '../entities/CastleBoss';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {SfxManager} from '../audio/SfxManager';import {getItemDefinition} from '../items/itemCatalog';
export class CastleScene extends Phaser.Scene{
 constructor(){super('CastleScene')}
 create(){this.switching=false;this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,140,560);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.loadGame();this.physics.world.setBounds(0,0,1920,1000);this.cameras.main.setBounds(0,0,1920,1152);this.cameras.main.setDeadzone(220,90);this.cameras.main.startFollow(this.player,true,0.12,0.12,0,-110);this.cameras.main.setRoundPixels(true);this.createWorld();this.spawnEnemies();this.setupHud();this.setupInput();this.death=new DeathOverlay(this);this.installUnload();this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.CastleScene,t=this.registry.get('transitionSpawn');if(save){this.player.loadState(save.player);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv);this.skillManager.load(save.skills);this.classManager.load(this.player,save.characterClass||this.player.characterClass)}else this.player.applyClass(this.registry.get('selectedClass')||'warrior');if(t?.scene==='CastleScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y);this.equip.sync()}
 createWorld(){this.add.tileSprite(0,0,1920,1152,'path').setOrigin(0);this.add.rectangle(0,0,1920,1152,0x160f21,.28).setOrigin(0);this.add.text(75,90,'CASTELO',{fontFamily:'Arial',fontSize:18,color:'#ecf0ff',fontStyle:'bold'});this.add.rectangle(70,500,110,120,0xc084fc,.10);this.add.text(125,475,'CAVERNA',{fontFamily:'Arial',fontSize:12,color:'#8cc0ff'}).setOrigin(.5)}
 spawnEnemies(){this.enemies=[new Enemy(this,500,260,'Guarda',{hp:76,attackDamage:16,xpReward:38}),new Enemy(this,760,380,'Mago da Coroa',{hp:100,attackDamage:20,xpReward:55}),new Enemy(this,950,500,'Cavaleiro',{hp:120,attackDamage:23,xpReward:65})];this.mini=new CastleMiniBoss(this,1200,420);this.boss=new CastleBoss(this,1580,420)}
 setupHud(){this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),onMenu:()=>this.goMenu(),worldWidth:1920,worldHeight:1152,localName:'CASTELO',markers:[{x:100,y:560,color:0xffd166,label:'Caverna'},{x:1580,y:420,color:0xff6b6b,label:'Rei'}]})}
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO)}
 update(){if(this.hud.handle({collect:()=>this.collect(),talk:()=>this.message('Não há NPCs seguros nesta região.'),afterAction:()=>this.saveGame()})){this.hud.update();return}if(this.player.isDead()){this.handleDeath();return}this.move();for(const e of this.enemies){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player);if(this.boss.isAlive()){this.boss.updateAI(this.player);this.combat.enemyAttack(this.boss,this.player)}const t=[...this.enemies,this.mini,this.boss];if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);for(let i=0;i<this.enemies.length;i++){const e=this.enemies[i];if(e.dead&&!e.respawnTimer){e.respawnTimer=this.time.delayedCall(9000,()=>{this.respawnOne(i);});}}this.loot.update(this.player.x,this.player.y);this.hud.setLocalName(this.player.x<220?'ENTRADA DO CASTELO':'CASTELO');this.hud.update();if(!this.boss.isAlive()&&!this.victoryTriggered){this.victoryTriggered=true;const relic=getItemDefinition('royal_signet');if(relic)this.inv.add(relic.id,1);this.saveGame();this.time.delayedCall(900,()=>this.scene.start('VictoryScene'))}if(this.player.x<150&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'CaveScene',x:1740,y:560});this.scene.start('CaveScene')}}
 move(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy))}
 collect(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame();this.hud.bottom.update()}}
 respawnOne(i){const p=[{x:500,y:260,name:'Guarda',stats:{hp:76,attackDamage:16,xpReward:38}},{x:760,y:380,name:'Mago da Coroa',stats:{hp:100,attackDamage:20,xpReward:55}},{x:950,y:500,name:'Cavaleiro',stats:{hp:120,attackDamage:23,xpReward:65}}][i];if(p)this.enemies[i]=new Enemy(this,p.x,p.y,p.name,p.stats)}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(180,560);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:old?.quests||[],worldFlags:old?.worldFlags||{},scenePositions:{...(old?.scenePositions||{}),[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 goMenu(){this.saveGame();this.scene.start('MenuScene')}
 installUnload(){this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.saveGame())}
 message(t){this.msg??=this.add.text(this.scale.width/2,this.scale.height-145,'',{fontFamily:'Arial',fontSize:12,color:'#fff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1200);this.msg.setText(t);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:1000,duration:500})}
}
