// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {CaveMiniBoss} from '../entities/CaveMiniBoss';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {SfxManager} from '../audio/SfxManager';
export class CaveScene extends Phaser.Scene{
 constructor(){super('CaveScene')}
 create(){this.switching=false;this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,220,760);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.loadGame();this.physics.world.setBounds(0,0,1920,1000);this.cameras.main.setBounds(0,0,1920,1152);this.cameras.main.setDeadzone(240,100);this.cameras.main.startFollow(this.player,true,.12,.12,0,-125);this.cameras.main.setRoundPixels(true);this.createWorld();this.spawnEnemies();this.setupHud();this.setupInput();this.death=new DeathOverlay(this);this.installUnload();this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.CaveScene,t=this.registry.get('transitionSpawn');if(save){this.player.loadState(save.player);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv);this.skillManager.load(save.skills);this.classManager.load(this.player,save.characterClass||this.player.characterClass)}else this.player.applyClass(this.registry.get('selectedClass')||'warrior');if(t?.scene==='CaveScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y);this.equip.sync()}
 createWorld(){this.add.tileSprite(0,0,1920,1152,'path').setOrigin(0);this.add.rectangle(0,0,1920,1152,0x080b13,.32).setOrigin(0);this.add.text(75,90,'CAVERNA',{fontFamily:'Arial',fontSize:18,color:'#ecf0ff',fontStyle:'bold'});this.forestPortal=this.add.zone(100,560,120,170);this.castlePortal=this.add.zone(1820,560,120,170);this.add.rectangle(100,560,120,170,0x73e6a8,.12);this.add.rectangle(1820,560,120,170,0xc084fc,.12);this.add.text(100,470,'PORTAL • FLORESTA',{fontFamily:'Arial',fontSize:12,color:'#73e6a8'}).setOrigin(.5);this.add.text(1820,470,'PORTAL • CASTELO',{fontFamily:'Arial',fontSize:12,color:'#c084fc'}).setOrigin(.5)}
 spawnEnemies(){this.spawnPoints=[{x:520,y:250,name:'Esqueleto',stats:{hp:55,attackDamage:13,xpReward:25}},{x:760,y:380,name:'Cultista',stats:{hp:65,attackDamage:15,xpReward:30}},{x:980,y:520,name:'Morcego Sombrio',stats:{hp:30,speed:110,attackDamage:10,xpReward:22}},{x:1280,y:760,name:'Morcego de Cristal',stats:{hp:48,speed:105,attackDamage:14,xpReward:34}},{x:1500,y:380,name:'Escavador Sombrio',stats:{hp:72,attackDamage:17,xpReward:42}}];this.enemies=this.spawnPoints.map(p=>new Enemy(this,p.x,p.y,p.name,p.stats));this.mini=new CaveMiniBoss(this,1250,420)}
 setupHud(){this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),onMenu:()=>this.goMenu(),worldWidth:1920,worldHeight:1152,localName:'CAVERNA',markers:[{x:110,y:560,color:0xffd166,label:'Floresta'},{x:1810,y:560,color:0xc084fc,label:'Castelo'}]})}
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO)}
 update(){if(this.hud.handle({collect:()=>this.collect(),talk:()=>this.message('Não há NPCs seguros nesta região.'),afterAction:()=>this.saveGame()})){this.hud.update();return}if(this.player.isDead()){this.handleDeath();return}const px=this.player.x,py=this.player.y;this.move();this.enforcePortals(px,py);for(const e of this.enemies){if(!e.dead){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}}this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player);const t=[...this.enemies,this.mini];if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);for(let i=0;i<this.enemies.length;i++){const e=this.enemies[i];if(e.dead&&!e.respawnTimer)e.respawnTimer=this.time.delayedCall(9000,()=>this.respawnOne(i))}this.loot.update(this.player.x,this.player.y);this.hud.setLocalName(this.getLocal());this.hud.update();if(this.forestPortal.getBounds().contains(this.player.x,this.player.y)&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'GreenWoodsScene',x:2220,y:760});this.scene.start('GreenWoodsScene')}if(this.castlePortal.getBounds().contains(this.player.x,this.player.y)&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'CastleScene',x:180,y:760});this.scene.start('CastleScene')}}
 enforcePortals(px,py){if(px<100&&this.player.x<100&&!this.forestPortal.getBounds().contains(this.player.x,this.player.y))this.player.x=px;if(px>1820&&this.player.x>1820&&!this.castlePortal.getBounds().contains(this.player.x,this.player.y))this.player.x=px}
 getLocal(){if(this.forestPortal.getBounds().contains(this.player.x,this.player.y))return'PORTAL DA FLORESTA';if(this.castlePortal.getBounds().contains(this.player.x,this.player.y))return'PORTAL DO CASTELO';return'CAVERNA'}
 move(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy))}
 collect(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame();this.hud.bottom.update()}}
 respawnOne(i){const p=this.spawnPoints[i];if(p)this.enemies[i]=new Enemy(this,p.x,p.y,p.name,p.stats)}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(220,760);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:old?.quests||[],scenePositions:{...(old?.scenePositions||{}),[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 goMenu(){this.saveGame();this.scene.start('MenuScene')}
 installUnload(){this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.saveGame())}
 message(t){this.msg??=this.add.text(this.scale.width/2,this.scale.height-145,'',{fontFamily:'Arial',fontSize:12,color:'#fff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1200);this.msg.setText(t);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:1000,duration:500})}
}
