// @ts-nocheck
import {Player} from '../entities/Player.ts';
import {Inventory} from '../inventory/Inventory.ts';
import {EquipmentManager} from '../equipment/EquipmentManager.ts';
import {AbilitySystem} from '../abilities/AbilitySystem.ts';
import {CombatSystem} from '../combat/CombatSystem.ts';
import {LootManager} from '../loot/LootManager.ts';
import {HUD} from '../ui/HUD.ts';
import {AbilityBar} from '../ui/AbilityBar.ts';
import {ForestMiniBoss} from '../entities/ForestMiniBoss.ts';
import {MiniBossBar} from '../ui/MiniBossBar.ts';
import {Enemy} from '../entities/Enemy.ts';
import {SaveManager} from '../save/SaveManager.ts';
export class GreenWoodsScene extends Phaser.Scene{constructor(){super('GreenWoodsScene')}create(){this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,120,500);const save=this.sm.load();if(save){this.player.loadState(save.player);this.inv.load(save.inventory)}this.equip=new EquipmentManager(this.player);this.equip.load(save?.equipment,this.inv);this.abilities=new AbilitySystem(this,this.player);this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.hud=new HUD(this,this.player);this.bar=new AbilityBar(this,this.abilities);this.add.tileSprite(0,0,1920,1152,'grass').setOrigin(0);this.add.text(960,50,'FLORESTA VERDE',{fontFamily:'Arial',fontSize:28,color:'#73e6a8'}).setOrigin(.5);this.enemies=[new Enemy(this,500,250,'Lobo',{hp:42,attackDamage:10,xpReward:18}),new Enemy(this,700,330,'Goblin',{hp:45,attackDamage:11,xpReward:20})];this.mini=new ForestMiniBoss(this,1150,450);this.mb=new MiniBossBar(this);this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.a=this.input.keyboard.addKey(32);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO);this.cam=this.cameras.main;this.cam.setBounds(0,0,1920,1152);this.physics.world.setBounds(0,0,1920,1152);this.cam.startFollow(this.player,true,.08,.08)}update(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy));for(const e of this.enemies)e.updateAI(this.player);this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player);const t=[...this.enemies,this.mini];if(Phaser.Input.Keyboard.JustDown(this.a))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);const d=this.loot.collectNear(this.player.x,this.player.y);this.loot.update(this.player.x,this.player.y);this.hud.update();this.bar.update();if(this.mini.isAlive()&&Phaser.Math.Distance.Between(this.player.x,this.player.y,this.mini.x,this.mini.y)<320)this.mb.show(this.mini);else this.mb.hide();if(this.player.x<70)this.scene.start('WorldScene');if(this.player.x>1760)this.scene.start('CaveScene')}}
