// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {ForestMiniBoss} from '../entities/ForestMiniBoss';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {ChoiceDialogueBox} from '../ui/ChoiceDialogueBox';import {Npc} from '../npc/Npc';import {SfxManager} from '../audio/SfxManager';
export class GreenWoodsScene extends Phaser.Scene{
 constructor(){super('GreenWoodsScene')}
 create(){this.switching=false;this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,100,560);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.loadGame();this.physics.world.setBounds(0,0,1920,1152);this.cameras.main.setBounds(0,0,1920,1152);this.cameras.main.setDeadzone(220,110);this.cameras.main.startFollow(this.player,true,0.12,0.12,0,-55);this.cameras.main.setRoundPixels(true);this.createWorld();this.createNpcs();this.spawnEnemies();this.setupHud();this.setupInput();this.death=new DeathOverlay(this);this.installUnload();this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.GreenWoodsScene,t=this.registry.get('transitionSpawn');if(save){this.player.loadState(save.player);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv);this.skillManager.load(save.skills);this.classManager.load(this.player,save.characterClass||this.player.characterClass)}else this.player.applyClass(this.registry.get('selectedClass')||'warrior');if(t?.scene==='GreenWoodsScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y);this.equip.sync()}
 createWorld(){this.add.tileSprite(0,0,1920,1152,'grass').setOrigin(0);this.add.rectangle(0,0,1920,1152,0x1f5030,.12).setOrigin(0);for(let x=190;x<1720;x+=190)for(let y=150;y<1000;y+=230)this.add.image(x,y,'tree-placeholder').setOrigin(.5).setDepth(5);this.add.rectangle(60,500,110,120,0x7ee0ff,.10);this.add.text(115,475,'CIDADE',{fontFamily:'Arial',fontSize:12,color:'#ffd166'}).setOrigin(.5);this.add.rectangle(1780,500,110,120,0x8cc0ff,.10);this.add.text(1780,430,'CAVERNA',{fontFamily:'Arial',fontSize:12,color:'#8cc0ff'}).setOrigin(.5)}
 createNpcs(){this.guide=new Npc(this,260,520,'Ranger',['A floresta é perigosa, mas a caverna guarda algo ainda pior.'])}
 spawnEnemies(){this.enemies=[new Enemy(this,520,260,'Lobo',{hp:42,attackDamage:10,xpReward:18}),new Enemy(this,760,350,'Goblin',{hp:45,attackDamage:11,xpReward:20}),new Enemy(this,960,500,'Morcego',{hp:28,speed:100,attackDamage:8,xpReward:16})];this.mini=new ForestMiniBoss(this,1280,420)}
 setupHud(){this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),onMenu:()=>this.goMenu(),worldWidth:1920,worldHeight:1152,localName:'FLORESTA VERDE',markers:[{x:90,y:560,color:0xffd166,label:'Cidade'},{x:1790,y:560,color:0x8cc0ff,label:'Caverna'}]});this.dialogue=new ChoiceDialogueBox(this);this.dialogueOpen=false}
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO)}
 update(){if(this.dialogueOpen){this.player.move(0,0);if(Phaser.Input.Keyboard.JustDown(this.dialogueF)||Phaser.Input.Keyboard.JustDown(this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC)))this.closeDialogue();return}if(this.hud.handle({collect:()=>this.collect(),talk:()=>this.talk(),afterAction:()=>this.saveGame()})){this.hud.update();return}if(this.player.isDead()){this.handleDeath();return}this.move();for(const e of this.enemies){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player);const t=[...this.enemies,this.mini];if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);for(let i=0;i<this.enemies.length;i++){const e=this.enemies[i];if(e.dead&&!e.respawnTimer){e.respawnTimer=this.time.delayedCall(9000,()=>{this.respawnOne(i);});}}this.loot.update(this.player.x,this.player.y);this.hud.setLocalName(this.player.x>1740?'PORTAL DA CAVERNA':'FLORESTA VERDE');this.hud.update();if(this.player.x<150&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'WorldScene',x:1660,y:350});this.scene.start('WorldScene')}if(this.player.x>1770&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'CaveScene',x:140,y:560});this.scene.start('CaveScene')}}
 move(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy))}
 collect(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame();this.hud.bottom.update()}}
 talk(){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.guide.x,this.guide.y);if(d>80){this.message('Aproxime-se do Ranger.');return}this.dialogueOpen=true;this.hud.openExternalModal();this.dialogueF=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);this.dialogue.open('Ranger','A caverna fica além das árvores. Prepare seu equipamento.',[{label:'Fechar',onSelect:()=>this.closeDialogue()}])}
 closeDialogue(){this.dialogue.close();this.dialogueOpen=false;this.hud.closeExternalModal();this.dialogueF?.destroy()}
 respawnOne(i){const p=[{x:520,y:260,name:'Lobo',stats:{hp:42,attackDamage:10,xpReward:18}},{x:760,y:350,name:'Goblin',stats:{hp:45,attackDamage:11,xpReward:20}},{x:960,y:500,name:'Morcego',stats:{hp:28,speed:100,attackDamage:8,xpReward:16}}][i];if(p)this.enemies[i]=new Enemy(this,p.x,p.y,p.name,p.stats)}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(180,560);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:old?.quests||[],scenePositions:{...(old?.scenePositions||{}),[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 goMenu(){this.saveGame();this.scene.start('MenuScene')}
 installUnload(){this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.saveGame())}
 message(t){this.msg??=this.add.text(this.scale.width/2,this.scale.height-145,'',{fontFamily:'Arial',fontSize:12,color:'#fff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1200);this.msg.setText(t);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:1000,duration:500})}
}
