// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {ForestMiniBoss} from '../entities/ForestMiniBoss';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {ChoiceDialogueBox} from '../ui/ChoiceDialogueBox';import {Npc} from '../npc/Npc';import {SfxManager} from '../audio/SfxManager';import {DungeonRune} from '../world/DungeonRune';import {RuinGuardian} from '../entities/RuinGuardian';import {ForestSpirit} from '../entities/ForestSpirit';import {ForestStalker} from '../entities/ForestStalker';import {ClareiraAlpha} from '../entities/ClareiraAlpha';import {SwampHag} from '../entities/SwampHag';import {DeepWoodStag} from '../entities/DeepWoodStag';import {ForestWardenElite} from '../entities/ForestWardenElite';import {Waystone} from '../world/Waystone';
export class GreenWoodsScene extends Phaser.Scene{
 constructor(){super('GreenWoodsScene')}
 create(){this.switching=false;this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,180,760);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.loadGame();this.physics.world.setBounds(0,0,2400,1350);this.cameras.main.setBounds(0,0,2400,1500);this.cameras.main.setDeadzone(260,100);this.cameras.main.startFollow(this.player,true,.12,.12,0,-110);this.cameras.main.setRoundPixels(true);this.createWorld();this.createNpcs();this.spawnEnemies();this.setupHud();this.setupInput();this.death=new DeathOverlay(this);this.installUnload();this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.GreenWoodsScene,t=this.registry.get('transitionSpawn');this.worldFlags=save?.worldFlags||this.registry.get('worldFlags')||{};this.registry.set('worldFlags',this.worldFlags);if(save){this.player.loadState(save.player);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv);this.skillManager.load(save.skills);this.classManager.load(this.player,save.characterClass||this.player.characterClass)}else this.player.applyClass(this.registry.get('selectedClass')||'warrior');if(t?.scene==='GreenWoodsScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y);this.equip.sync()}
 createWorld(){this.add.tileSprite(0,0,2400,1500,'grass').setOrigin(0);this.add.rectangle(0,0,2400,1500,0x1f5030,.10).setOrigin(0);
  this.add.rectangle(760,480,680,520,0x2b6b3d,.18).setOrigin(0);this.add.text(1100,505,'CLAREIRA DO NASCENTE',{fontFamily:'Arial',fontSize:16,color:'#73e6a8',fontStyle:'bold'}).setOrigin(.5);
  this.add.rectangle(1580,130,700,400,0x315e46,.22).setOrigin(0);this.add.text(1930,155,'PÂNTANO SOMBRIO',{fontFamily:'Arial',fontSize:16,color:'#7ee0ff',fontStyle:'bold'}).setOrigin(.5);
  this.add.rectangle(300,130,650,360,0x4a4062,.18).setOrigin(0);this.add.text(625,155,'RUÍNAS ANTIGAS',{fontFamily:'Arial',fontSize:16,color:'#d2b3ff',fontStyle:'bold'}).setOrigin(.5);
  this.add.rectangle(1570,850,720,520,0x284f35,.16).setOrigin(0);this.add.text(1930,875,'BOSQUE PROFUNDO',{fontFamily:'Arial',fontSize:16,color:'#c8d1ea',fontStyle:'bold'}).setOrigin(.5);
  this.add.rectangle(260,1080,520,300,0x3f385f,.18).setOrigin(0);this.add.text(520,1105,'PONTE INTERDITADA',{fontFamily:'Arial',fontSize:13,color:'#ffb36b',fontStyle:'bold'}).setOrigin(.5);
  for(let x=140;x<2320;x+=170)for(let y=120;y<1320;y+=230){if((x+y)%3!==0)this.add.rectangle(x,y,34,54,0x285a34,1).setOrigin(.5).setDepth(5);this.add.circle(x,y-18,22,0x397a45,1).setDepth(6)}
  this.cityGate=this.add.zone(110,760,100,150);this.add.rectangle(110,760,100,150,0xffd166,.10).setOrigin(.5).setDepth(3);this.add.text(110,660,'PORTAL DA CIDADE',{fontFamily:'Arial',fontSize:12,color:'#ffd166'}).setOrigin(.5).setDepth(3);
  this.cavePortal=this.add.zone(2280,760,100,170);this.add.rectangle(2280,760,100,170,0x8cc0ff,.12).setOrigin(.5).setDepth(3);this.add.text(2280,660,'PORTAL • CAVERNA',{fontFamily:'Arial',fontSize:12,color:'#8cc0ff'}).setOrigin(.5).setDepth(3);
  this.bridgeZone=this.add.zone(520,1390,180,80);this.add.rectangle(520,1390,260,120,0x3e2a28,.22).setOrigin(.5).setDepth(2);
 }
 createNpcs(){this.guide=new Npc(this,380,780,'Aren Valebosque',['A floresta é enorme e cada região tem perigos diferentes.'],{role:'Ranger'});this.bridgeBuilder=new Npc(this,620,1270,'Edrin Halvek',['As vinhas continuam surgindo, mesmo depois de cortarmos as raízes. Parece uma maldição.','Sem quebrar essa maldição não consigo reconstruir a ponte para Valedouro. Dizem que sobreviventes daquela cidade precisam de ajuda.'],{role:'Construtor da Ponte'});this.ruinsScholar=new Npc(this,800,300,'Professor Cael',['Obrigado por eliminar o Guardião das Ruínas. Eu estava tentando decifrar estas runas, mas não está sendo fácil.','Há algo nestes símbolos que parece apontar para antigas masmorras. Talvez, com tempo, eu descubra como romper os selos.'],{role:'Erudito das Ruínas'});this.ruinsScholar.setVisible(!!this.worldFlags?.ruinsGuardianDefeated);this.spawnRuinsScholarIfNeeded()}
 spawnRuinsScholarIfNeeded(){const flags=this.sm.load()?.worldFlags||this.worldFlags||{};this.worldFlags=flags;this.ruinsScholar?.setVisible(!!flags.ruinsGuardianDefeated)}
 spawnRuinsScholar(){if(!this.ruinsScholar)this.ruinsScholar=new Npc(this,800,300,'Professor Cael',['Obrigado por eliminar o Guardião das Ruínas. Eu estava tentando decifrar estas runas, mas não está sendo fácil.','Há algo nestes símbolos que parece apontar para antigas masmorras. Talvez, com tempo, eu descubra como romper os selos.'],{role:'Erudito das Ruínas'});this.ruinsScholar.setVisible(true);this.ruinsScholar.setDepth(40)}
 spawnEnemies(){const flags=this.worldFlags||{};this.ruinGuardian=flags.ruinsGuardianDefeated?null:new RuinGuardian(this,620,330);this.spawnPoints=[
{x:900,y:700,name:'Lobo da Clareira',stats:{hp:42,attackDamage:10,xpReward:18,tint:0x73e6a8}},
{x:1040,y:850,name:'Goblin Lenhador',stats:{hp:45,attackDamage:11,xpReward:20,tint:0xa0c77b}},
{x:1720,y:300,name:'Sapo Sombrio',stats:{hp:50,attackDamage:12,xpReward:24,tint:0x6ba56e}},
{x:2010,y:420,name:'Bruxa do Pântano',stats:{hp:62,attackDamage:15,xpReward:30,tint:0x8aa4d6}},
{x:1770,y:1030,name:'Cervo Corrompido',stats:{hp:58,attackDamage:14,xpReward:32,tint:0xc084fc}},
{x:2100,y:1180,name:'Morcego do Bosque',stats:{hp:34,speed:105,attackDamage:10,xpReward:26,tint:0x8cc0ff}},
{x:1250,y:980,name:'Lobo da Floresta',stats:{hp:46,attackDamage:11,xpReward:22,tint:0x5f8f52}},
{x:1450,y:700,name:'Guardião da Floresta',stats:{hp:72,attackDamage:17,xpReward:40,tint:0x7b5aa6}}
];this.enemies=this.spawnPoints.map(p=>new Enemy(this,p.x,p.y,p.name,p.stats));this.forestSpiritSpawns=[new ForestSpirit(this,600,600),new ForestSpirit(this,1360,350),new ForestSpirit(this,1120,1180),new ForestStalker(this,680,920),new ForestStalker(this,1500,900)];this.regionElites=[new ClareiraAlpha(this,1180,760),new SwampHag(this,2080,250),new DeepWoodStag(this,1840,980),new ForestWardenElite(this,1380,1120)];this.mini=new ForestMiniBoss(this,2050,1180);this.miniRuinHandled=!!flags.ruinsGuardianDefeated}
setupHud(){this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),onMenu:()=>this.goMenu(),worldWidth:2400,worldHeight:1500,localName:'FLORESTA • CLAREIRA',markers:[{x:110,y:760,color:0xffd166,label:'Cidade'},{x:2280,y:760,color:0x8cc0ff,label:'Caverna'},{x:520,y:1260,color:0xffb36b,label:'Ponte'}]});this.dialogue=new ChoiceDialogueBox(this);this.dialogueOpen=false;this.dungeonRunes=[];this.createDungeonRunes();this.waystone=new Waystone(this,1150,1020,'FLORESTA')}
 createDungeonRunes(){this.dungeonRunes=[new DungeonRune(this,1120,760,'Masmorra da Clareira','CLAREIRA DO NASCENTE'),new DungeonRune(this,1930,340,'Masmorra do Pântano','PÂNTANO SOMBRIO'),new DungeonRune(this,1930,1090,'Masmorra do Bosque','BOSQUE PROFUNDO'),new DungeonRune(this,1250,560,'Masmorra da Floresta','FLORESTA VERDE')]} 
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.fKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO)}
 movePlayer(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);const moved=this.player.move(dx,dy);if(typeof this.player.playMove==='function')this.player.playMove(moved)}
 update(){this.updateNpcPrompts();if(this.dialogueOpen){this.player.move(0,0);if(Phaser.Input.Keyboard.JustDown(this.dialogueF)||Phaser.Input.Keyboard.JustDown(this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC)))this.closeDialogue();return}if(Phaser.Input.Keyboard.JustDown(this.fKey)){const rune=this.findNearbyRune();if(rune){this.readRune(rune);return}if(this.isNearWaystone()){this.readWaystone();return}if(this.findNearbyNpc()){this.talk();return}}if(this.hud.handle({collect:()=>this.collect(),talk:()=>this.talk(),afterAction:()=>this.saveGame()})){this.hud.update();return}if(this.player.isDead()){this.handleDeath();return}this.waystone.updatePrompt(this.player.x,this.player.y);this.movePlayer();this.enforceForestExits(this.player.x,this.player.y);for(const e of this.enemies){if(!e.dead){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}else if(!e.respawnTimer)e.respawnTimer=this.time.delayedCall(9000,()=>this.respawnOne(this.enemies.indexOf(e)))}for(const e of this.forestSpiritSpawns||[]){if(!e.dead){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}}for(const e of this.regionElites||[]){if(!e.dead){e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}else if(!e.respawnTimer)e.respawnTimer=this.time.delayedCall(16000,()=>this.respawnRegionElite(e))}if(this.mini&&!this.mini.dead){this.mini.updateAI(this.player);this.combat.enemyAttack(this.mini,this.player)}if(this.ruinGuardian){this.ruinGuardian.updateAI(this.player);this.combat.enemyAttack(this.ruinGuardian,this.player);if(this.ruinGuardian.dead&&!this.miniRuinHandled){this.miniRuinHandled=true;this.worldFlags={...(this.worldFlags||{}),ruinsGuardianDefeated:true};this.registry.set('worldFlags',this.worldFlags);this.saveGame();this.spawnRuinsScholar()}}const t=[...this.enemies,...(this.forestSpiritSpawns||[]),...(this.regionElites||[]),...(this.mini?[this.mini]:[]),...(this.ruinGuardian?[this.ruinGuardian]:[])];if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,t);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',t);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',t);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',t);this.loot.update(this.player.x,this.player.y);this.hud.setLocalName(this.getLocal());this.hud.update();if(this.cavePortal.getBounds().contains(this.player.x,this.player.y)&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'CaveScene',x:220,y:760,hp:this.player.hp,mana:this.player.mana});this.scene.start('CaveScene')}if(this.cityGate.getBounds().contains(this.player.x,this.player.y)&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'WorldScene',x:3780,y:650,hp:this.player.hp,mana:this.player.mana});this.scene.start('WorldScene')}}
 isNearWaystone(){return this.waystone&&Phaser.Math.Distance.Between(this.player.x,this.player.y,this.waystone.x,this.waystone.y)<=85}
 readWaystone(){this.hud.openExternalModal();this.dialogueOpen=true;this.dialogueF=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);this.dialogue.open('Marco de Senda',this.waystone.readMessage(),[{label:'Fechar',onSelect:()=>this.closeDialogue()}])}
 respawnRegionElite(e){const C=e.constructor;const fresh=new C(this,e.x,e.y);const idx=this.regionElites.indexOf(e);if(idx>=0)this.regionElites[idx]=fresh}
 getLocal(){if(this.player.x>=260&&this.player.x<=780&&this.player.y>=1080)return'FLORESTA • PONTE INTERDITADA';if(this.player.x>=300&&this.player.x<=950&&this.player.y>=130&&this.player.y<=490)return'FLORESTA • RUÍNAS ANTIGAS';if(this.player.x>=1580&&this.player.x<=2280&&this.player.y>=130&&this.player.y<=530)return'FLORESTA • PÂNTANO';if(this.player.x>=1570&&this.player.x<=2290&&this.player.y>=850&&this.player.y<=1370)return'FLORESTA • BOSQUE PROFUNDO';if(this.player.x>=760&&this.player.x<=1440&&this.player.y>=480&&this.player.y<=1000)return'FLORESTA • CLAREIRA';return'FLORESTA VERDE'}
 enforceForestExits(px,py){const x=this.player.x,y=this.player.y;const eastCross=(px<=2280&&x>2280)||(px>=2280&&x<2280);const westCross=(px<=110&&x<110)||(px>=110&&x>110);if(eastCross&&!this.cavePortal.getBounds().contains(x,y)&&!this.cavePortal.getBounds().contains(px,py))this.player.x=px;if(westCross&&!this.cityGate.getBounds().contains(x,y)&&!this.cityGate.getBounds().contains(px,py))this.player.x=px;}
 updateNpcPrompts(){for(const n of [this.guide,this.bridgeBuilder,this.ruinsScholar].filter(n=>n&&n.visible)){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);n.setPrompt('F • Conversar');n.setNearby(d<90)}for(const rune of this.dungeonRunes)rune.updatePrompt(this.player.x,this.player.y)}
 collect(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame();this.hud.bottom.update()}}
 findNearbyRune(){let best=null,dist=Infinity;for(const rune of this.dungeonRunes){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,rune.x,rune.y);if(d<dist){dist=d;best=rune}}return best&&dist<=72?best:null}
 readRune(rune){this.hud.openExternalModal();this.dialogueOpen=true;this.dialogueF=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);this.runeBeingRead=rune;this.dialogue.open('Runa Antiga',`Aqui existia a entrada para a ${rune.dungeonName}, mas parece fechada agora.\n\nUma força antiga selou esta passagem.`,[{label:'Fechar',onSelect:()=>this.closeRune()}])}
 closeRune(){this.dialogue.close();this.dialogueOpen=false;this.hud.closeExternalModal();this.dialogueF?.destroy();this.runeBeingRead=null}
 findNearbyNpc(){const np=[this.guide,this.bridgeBuilder,this.ruinsScholar].filter(n=>n&&n.visible);let near=null,b=Infinity;for(const n of np){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<b){b=d;near=n}}return near&&b<=90?near:null}
 talk(){const np=[this.guide,this.bridgeBuilder,this.ruinsScholar].filter(n=>n&&n.visible);let near=null,b=Infinity;for(const n of np){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<b){b=d;near=n}}if(!near||b>90){this.message('Aproxime-se de um NPC para conversar.');return}this.dialogueOpen=true;this.hud.openExternalModal();this.dialogueF=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);let body=near.text.join('\n\n');if(near===this.bridgeBuilder&&this.inv.has('royal_signet'))body='O Selo Real de Aether funciona! As vinhas estão morrendo de verdade.\n\nAgora posso começar a reconstruir a ponte para Valedouro. Há sobreviventes naquela cidade que precisam de ajuda.';if(near===this.ruinsScholar)body=near.text.join('\n\n');this.dialogue.open(near.npcName,body,[{label:'Fechar',onSelect:()=>this.closeDialogue()}])}
 closeDialogue(){this.dialogue.close();this.dialogueOpen=false;this.hud.closeExternalModal();this.dialogueF?.destroy();this.runeBeingRead=null}
 respawnOne(i){const p=this.spawnPoints[i];if(p)this.enemies[i]=new Enemy(this,p.x,p.y,p.name,p.stats)}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(180,760);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:old?.quests||[],worldFlags:old?.worldFlags||{},scenePositions:{...(old?.scenePositions||{}),[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 goMenu(){this.saveGame();this.scene.start('MenuScene')}
 installUnload(){this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.saveGame())}
 message(t){this.msg??=this.add.text(this.scale.width/2,this.scale.height-145,'',{fontFamily:'Arial',fontSize:12,color:'#fff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1200);this.msg.setText(t);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:1000,duration:500})}
}
