// @ts-nocheck
import {ScreenFade} from '../ui/ScreenFade';
export class OptionsScene extends Phaser.Scene{
 constructor(){super('OptionsScene')}
 create(){this.fade=new ScreenFade(this);this.panelOpen=false;this.esc=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC);this.add.text(480,70,'OPÇÕES / SOBRE',{fontFamily:'Arial',fontSize:32,color:'#ecf0ff',fontStyle:'bold'}).setOrigin(.5);this.addButton('CONTROLES',210,()=>this.showPanel('CONTROLES',`WASD / Setas — mover\nEspaço — ataque básico\nQ — habilidade principal\n1 — habilidade secundária\n2 — mobilidade\nH — poção de HP\nM — poção de Mana\nE — coletar/interagir\nF — conversar\nI — inventário\nK — skills\nR — equipar\nT — loja (Mercador)\nC — controles durante o jogo\nP — pausa\nEsc — fechar janela`));this.addButton('SOBRE',290,()=>this.showPanel('SOBRE',`Legends of Aether é um RPG de ação 2D para navegador.\n\nExplore Aether, enfrente monstros corrompidos, escolha sua classe, encontre equipamentos e descubra o que aconteceu com o antigo reino.\n\nVersão 0.1.4 — Alpha`));this.addButton('VOLTAR AO MENU',390,()=>this.fade.out(()=>this.scene.start('MenuScene')));this.fade.in()}
 update(){if(this.panelOpen&&Phaser.Input.Keyboard.JustDown(this.esc))this.closePanel()}
 addButton(t,y,cb){this.add.text(480,y,t,{fontFamily:'Arial',fontSize:20,color:'#ecf0ff',backgroundColor:'#24314d',padding:14}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerdown',cb)}
 showPanel(title,body){this.closePanel();this.panelOpen=true;this.panel=this.add.rectangle(480,300,700,360,0x101827,.99).setStrokeStyle(2,0x4b5f87,1);this.pt=this.add.text(480,160,title,{fontFamily:'Arial',fontSize:24,color:'#ffd166',fontStyle:'bold'}).setOrigin(.5);this.pb=this.add.text(480,245,body,{fontFamily:'Arial',fontSize:16,color:'#c8d1ea',align:'center',wordWrap:{width:600}}).setOrigin(.5);this.pc=this.add.text(480,445,'Esc — fechar',{fontFamily:'Arial',fontSize:13,color:'#9aa8c7',backgroundColor:'#24314d',padding:8}).setOrigin(.5).setInteractive({useHandCursor:true});this.pc.on('pointerdown',()=>this.closePanel())}
 closePanel(){if(!this.panelOpen)return;[this.panel,this.pt,this.pb,this.pc].forEach(o=>o?.destroy());this.panelOpen=false}
}
