// @ts-nocheck
import {Player} from '../entities/Player';import {Enemy} from '../entities/Enemy';import {Inventory} from '../inventory/Inventory';import {EquipmentManager} from '../equipment/EquipmentManager';import {AbilitySystem} from '../abilities/AbilitySystem';import {CombatSystem} from '../combat/CombatSystem';import {LootManager} from '../loot/LootManager';import {SaveManager} from '../save/SaveManager';import {ClassManager} from '../character/ClassManager';import {SkillManager} from '../skills/SkillManager';import {MapHud} from '../ui/MapHud';import {DeathOverlay} from '../ui/DeathOverlay';import {Npc} from '../npc/Npc';import {WanderingNpc} from '../npc/WanderingNpc';import {ShopPanel} from '../shop/ShopPanel';import {ChoiceDialogueBox} from '../ui/ChoiceDialogueBox';import {SfxManager} from '../audio/SfxManager';import {QuestManager} from '../quests/QuestManager';
export class WorldScene extends Phaser.Scene{
 constructor(){super('WorldScene')}
 create(){this.switching=false;this.sm=new SaveManager();this.inv=new Inventory();this.player=new Player(this,180,350);this.classManager=new ClassManager();this.skillManager=new SkillManager(this.player);this.player.scene.skillManager=this.skillManager;this.equip=new EquipmentManager(this.player);this.sfx=new SfxManager(this);this.player.scene.sfx=this.sfx;this.loot=new LootManager(this,this.inv);this.combat=new CombatSystem(this,this.loot);this.abilities=new AbilitySystem(this,this.player);this.questManager=new QuestManager();this.loadGame();this.physics.world.setBounds(0,0,1920,1152);this.cameras.main.setBounds(0,0,1920,1152);this.cameras.main.startFollow(this.player,true,0.12,0.12);this.cameras.main.setRoundPixels(true);this.createWorld();this.cameras.main.centerOn(this.player.x,this.player.y);this.createNpcs();this.spawnEnemies();this.setupInput();this.setupHud();this.installUnload();this.saveGame()}
 loadGame(){const save=this.sm.load(),pos=save?.scenePositions?.WorldScene,t=this.registry.get('transitionSpawn');if(save){this.player.loadState(save.player);this.inv.load(save.inventory);this.equip.load(save.equipment,this.inv);this.skillManager.load(save.skills);this.questManager.load(save.quests);this.classManager.load(this.player,save.characterClass||this.player.characterClass)}else{this.player.applyClass(this.registry.get('selectedClass')||'warrior');this.registry.remove('selectedClass');this.inv.add('healing_potion',2);this.inv.add('mana_potion',2);this.player.gold=25}if(t?.scene==='WorldScene'){this.player.setPosition(t.x,t.y);this.registry.remove('transitionSpawn')}else if(pos)this.player.setPosition(pos.x,pos.y);this.equip.sync()}
 createWorld(){this.add.tileSprite(0,0,1920,1152,'grass').setOrigin(0);this.add.rectangle(0,0,1920,1152,0x16301f,.06).setOrigin(0);this.add.text(55,55,'CIDADE DE AETHER',{fontFamily:'Arial',fontSize:18,color:'#ecf0ff',fontStyle:'bold'});this.safeZone=this.add.rectangle(90,90,650,430,0x24314d,.12).setOrigin(0).setDepth(1);this.add.text(115,118,'ÁREA SEGURA',{fontFamily:'Arial',fontSize:14,color:'#73e6a8',fontStyle:'bold'}).setDepth(2);this.add.rectangle(760,90,990,650,0x7b3d2a,.08).setOrigin(0);this.add.text(1270,110,'ARREDORES DA CIDADE — PERIGO',{fontFamily:'Arial',fontSize:15,color:'#ffb36b'}).setOrigin(.5).setDepth(2);this.forestPortal=this.add.zone(1745,360,90,140);this.add.rectangle(1745,360,90,140,0x73e6a8,.12).setDepth(3);this.add.text(1745,290,'PORTAL • FLORESTA',{fontFamily:'Arial',fontSize:12,color:'#73e6a8'}).setOrigin(.5).setDepth(3)}
 createNpcs(){this.merchant=new Npc(this,260,230,'Mercador',['Tenho suprimentos para quem pretende atravessar os arredores.'],{shop:true});this.blacksmith=new Npc(this,420,230,'Ferreiro',['Minha ferraria ainda está sendo reconstruída. Minhas ferramentas desapareceram durante a invasão.','Quando eu recuperar minhas ferramentas, poderei trabalhar novamente.']);this.healer=new Npc(this,580,230,'Curandeiro',['Perdi minha fé depois dos acontecimentos sombrios. Não consigo invocar minha bênção agora.','Talvez, quando minha fé retornar, eu possa ajudar os feridos novamente.']);this.questNpc=new Npc(this,320,340,'Elder Mira',['A floresta ficou perigosa. Se trouxer provas dos monstros, conversaremos sobre o assunto.']);this.walkers=[new WanderingNpc(this,470,360,'Morador',['A praça ainda é o lugar mais seguro de Aether.']),new WanderingNpc(this,560,360,'Viajante',['Ouvi rumores sobre o castelo.'])]}
 spawnEnemies(){this.enemies=[new Enemy(this,900,260,'Goblin',{hp:34,xpReward:14,attackDamage:8}),new Enemy(this,1120,440,'Lobo',{hp:42,xpReward:18,attackDamage:10}),new Enemy(this,1380,300,'Goblin',{hp:38,xpReward:16,attackDamage:9})]}
 setupInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('W,A,S,D');this.attackKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.q=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.Q);this.one=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.two=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO);this.eKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.E);this.fKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);this.tKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.T);this.escKey=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ESC);this.shopOne=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.ONE);this.shopTwo=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.TWO);this.shopThree=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.THREE);this.shopClose=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.T)}
 setupHud(){this.hud=new MapHud(this,{player:this.player,inventory:this.inv,equipment:this.equip,abilities:this.abilities,skills:this.skillManager,save:()=>this.saveGame(),onMenu:()=>this.goMenu(),worldWidth:1920,worldHeight:1152,localName:'CIDADE DE AETHER',markers:[{x:1745,y:360,color:0x73e6a8,label:'Floresta'}]});this.shop=new ShopPanel(this,this.player,this.inv);this.dialogue=new ChoiceDialogueBox(this);this.dialogueOpen=false;this.shop.visible=false;this.death=new DeathOverlay(this)}
 update(){this.updateNpcPrompts();if(this.dialogueOpen){this.player.move(0,0);if(Phaser.Input.Keyboard.JustDown(this.fKey)||Phaser.Input.Keyboard.JustDown(this.escKey))this.closeDialogue();return}if(this.shop.visible){this.player.move(0,0);this.handleShop();return}if(this.hud.handle({collect:()=>this.collectLoot(),talk:()=>this.tryTalk(),shop:()=>this.tryShop(),afterAction:()=>this.saveGame()})){this.hud.update();return}if(this.player.isDead()){this.handleDeath();return}const inside=this.player.x<760&&this.player.y<600;this.move();for(const e of this.enemies){if(this.player.x<760&&this.player.y<600){e.body.setVelocity(0,0);continue}e.updateAI(this.player);this.combat.enemyAttack(e,this.player)}this.loot.update(this.player.x,this.player.y);if(Phaser.Input.Keyboard.JustDown(this.attackKey))this.combat.playerAttack(this.player,this.enemies);if(Phaser.Input.Keyboard.JustDown(this.q))this.abilities.use('primary',this.enemies);if(Phaser.Input.Keyboard.JustDown(this.one))this.abilities.use('secondary',this.enemies);if(Phaser.Input.Keyboard.JustDown(this.two))this.abilities.use('mobility',this.enemies);const local=this.player.x<760&&this.player.y<600?'CIDADE DE AETHER':this.player.x<1690?'ARREDORES DA CIDADE':'PORTAL DA FLORESTA';this.hud.setLocalName(local);this.hud.update();if(this.player.x>1690&&!this.switching){this.switching=true;this.saveGame();this.registry.set('transitionSpawn',{scene:'GreenWoodsScene',x:90,y:560});this.scene.start('GreenWoodsScene')}}
 move(){const dx=(this.cursors.right.isDown||this.keys.D.isDown?1:0)-(this.cursors.left.isDown||this.keys.A.isDown?1:0);const dy=(this.cursors.down.isDown||this.keys.S.isDown?1:0)-(this.cursors.up.isDown||this.keys.W.isDown?1:0);this.player.playMove(this.player.move(dx,dy))}
 updateNpcPrompts(){const list=[this.merchant,this.blacksmith,this.healer,this.questNpc,...(this.walkers||[])].filter(Boolean);for(const n of list){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(n===this.merchant)n.setPrompt(d<80?'F • Conversar   T • Loja':'F • Conversar');else n.setPrompt('F • Conversar');n.setNearby(d<80)}}
 tryShop(){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.merchant.x,this.merchant.y);if(d>80){this.showActionMessage('Aproxime-se do Mercador para abrir a loja.');return}this.shop.toggle();this.shop.refresh();this.hud.openExternalModal()}
 handleShop(){if(Phaser.Input.Keyboard.JustDown(this.shopClose)||Phaser.Input.Keyboard.JustDown(this.escKey)){this.shop.toggle();this.hud.closeExternalModal();return}if(Phaser.Input.Keyboard.JustDown(this.shopOne))this.shop.buy(0);if(Phaser.Input.Keyboard.JustDown(this.shopTwo))this.shop.buy(1);if(Phaser.Input.Keyboard.JustDown(this.shopThree))this.shop.buy(2);this.shop.refresh()}
 tryTalk(){const npcs=[this.merchant,this.blacksmith,this.healer,this.questNpc,...(this.walkers||[])];let near=null,b=Infinity;for(const n of npcs){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<b){b=d;near=n}}if(!near||b>80){this.showActionMessage('Aproxime-se de um NPC para conversar.');return}this.dialogueOpen=true;this.hud.openExternalModal();this.dialogueF=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.F);const choices=[];if(near===this.merchant)choices.push({label:'Abrir loja',onSelect:()=>{this.closeDialogue();this.shop.toggle();this.shop.refresh();this.hud.openExternalModal()}});choices.push({label:'Fechar',onSelect:()=>this.closeDialogue()});this.dialogue.open(near.npcName,near.text.join('\n\n'),choices)}
 closeDialogue(){this.dialogue.close();this.dialogueOpen=false;this.hud.closeExternalModal();this.dialogueF?.destroy()}
 collectLoot(){const d=this.loot.collectNear(this.player.x,this.player.y);if(d){this.sfx.pickup();this.saveGame();this.hud.bottom.update()}}
 handleDeath(){if(this.respawnTimer)return;this.hud.openExternalModal();this.death.show('Respawn em 2 segundos');this.respawnTimer=this.time.delayedCall(2000,()=>{this.player.respawn(180,350);this.hud.closeExternalModal();this.death.hide();this.respawnTimer=null;this.saveGame()})}
 saveGame(){const old=this.sm.load();this.sm.save({version:1,savedAt:Date.now(),lastScene:this.scene.key,player:this.player.serialize(),characterClass:this.player.characterClass,skills:this.skillManager.serialize(),inventory:this.inv.serialize(),equipment:this.equip.serialize(),quests:this.questManager.serialize?.()||[],scenePositions:{...(old?.scenePositions||{}),WorldScene:{x:this.player.x,y:this.player.y},[this.scene.key]:{x:this.player.x,y:this.player.y}}})}
 goMenu(){this.saveGame();this.scene.start('MenuScene')}
 installUnload(){this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.saveGame());window.addEventListener('beforeunload',this._unload=()=>this.saveGame())}
 showActionMessage(m){this.msg??=this.add.text(this.scale.width/2,this.scale.height-145,'',{fontFamily:'Arial',fontSize:12,color:'#ecf0ff',backgroundColor:'#182033',padding:7}).setOrigin(.5).setScrollFactor(0).setDepth(1200);this.msg.setText(m);this.msg.setAlpha(1);this.tweens.killTweensOf(this.msg);this.tweens.add({targets:this.msg,alpha:0,delay:1000,duration:500})}
}
